module.exports = {
	"domains": ["gmail", "hotmail", "yahoo", "github"],
	"extensions": [".com", ".fr", ".uk", ".eu", ".cn"],
	"genders": ["m", "f"],
	"names": {
		"m": ["Henri", "Paul", "Romain", "Romuald", "Florian", "Ruben", "Pierre", "Joris", "Nicolas", "Youri"],
		"f": ["Karen", "Marie", "Paola", "Julia", "Ming", "Tiffany", "Camille", "Samira", "Johanna"]
	},
	"lastNames": ["De la Roche", "de Montegut", "Monnerau", "Roch", "Aubin", "Duval", "LaSalle", "Michelin", "Valois", "Bonaparte"],
	"letters": ['a',
				'b',
				'c',
				'd',
				'e',
				'f',
				'g',
				'h',
				'i',
				'j',
				'k',
				'l',
				'm',
				'n',
				'o',
				'p',
				'q',
				'r',
				's',
				't',
				'u',
				'v',
				'w',
				'x',
				'y' ]
}